### PR TITLE
Mobile ux UI

### PR DESCRIPTION
**Pull request by zamrokk**
listing here improvements

### CODE REVIEW

**Comment by zamrokk** [comment]
while displaying on iphone view

image

**Comment by zamrokk** [comment]
combobox weird display on colors

image

**Comment by zamrokk** [comment]
When connected, the address is very big and connect well fit on the page

image

**Comment by zamrokk** [comment]
It should be better to gather all in the app icon

image

**Comment by zamrokk** [comment]
it is too small

image

**Comment by zamrokk** [comment]
For the mobile version, we should be able to fit all info on a single page without being forced to scroll down. Even removing the footer "Powered by Marigold" if necessaey 

image

**Comment by vanessamontesb** [comment]
Updated: 
Screen Shot 2022-09-08 at 4 23 00 PM
Screen Shot 2022-09-08 at 2 26 56 PM
Screen Shot 2022-09-08 at 2 27 03 PM
Screen Shot 2022-09-08 at 2 27 09 PM
Screen Shot 2022-09-08 at 3 24 05 PM

**Comment by zamrokk** [comment]
image

border square vs smooth ... ? 

I think we should just have square fullwith with transparent % (like this we see a bit the planet on bakcground)

**Comment by zamrokk** [comment]
image

separate with a line "apps" from "documentation" items. Add a small title to each section. On click do a "_blank" , don't do fored redirection, just open a new tab

**Comment by zamrokk** [comment]
still not fitting in 1 page 

image

remove the padding of menu white underline item

**Comment by zamrokk** [comment]
Claim should look like the other pages , full screen, no border left or right, we need maximum wifth to displau max information 

image

**Comment by zamrokk** [comment]
is it possible **onHover** to display the title of the menu items ? It could help the user

**Comment by zamrokk** [comment]
deposit and withdraw page does not fit on screen without scrolling ... 

image


also I have lost a part of the components on bottom, see the destop version here 

image

**Comment by zamrokk** [comment]
desktop frames not having same width (why L1 Claim is different?)

image
image

**Comment by zamrokk** [comment]
Can you make a pending animation when amount are fetching ?

image


meaning, when `undefined`, then replace it by animated skeleton  https://mui.com/material-ui/react-skeleton/

**Comment by zamrokk** [comment]
The same way titles are done here 
image

First part is "L2 network"
Second parts are "L1 account" & "L2 account"

image

**Comment by zamrokk** [comment]
not aligned 

image

**Comment by vanessamontesb** [comment]
Updated
Screen Shot 2022-09-22 at 3 46 04 PM
Screen Shot 2022-09-22 at 3 46 09 PM
Screen Shot 2022-09-22 at 5 12 57 PM
Screen Shot 2022-09-22 at 5 15 55 PM

**Comment by zamrokk** [comment]
image

**Comment by zamrokk** [comment]
alignment still not ok
L1 claim is still not centered like all other frames  (too on the right side)

image

image

**Comment by zamrokk** [comment]
Menu almost ok, but "L2 account" has to be under

image

**Pull request merged**
