### PR TITLE
UI development

### PR DESCRIPTION
**Pull request by vanessamontesb**
Screen Shot 2022-11-13 at 6 53 23 PM
Screen Shot 2022-11-13 at 6 53 33 PM
Screen Shot 2022-11-13 at 6 54 20 PM
Screen Shot 2022-11-13 at 6 54 45 PM
Screen Shot 2022-11-13 at 6 54 56 PM
Screen Shot 2022-11-13 at 6 55 10 PM
Screen Shot 2022-11-13 at 6 55 39 PM
Screen Shot 2022-11-13 at 6 55 50 PM
Screen Shot 2022-11-13 at 6 56 11 PM

### CODE REVIEW

**Comment by zamrokk** [comment]
would it be possible to change black color of icons to this almost black background we have ? Is because we see the menu before login, not nice :/

image

**Comment by zamrokk** [comment]
some have white borders but other not ? why ?

image

**Comment by zamrokk** [comment]
inner black border visible   +   text "Available balance" is not aligned left

image

**Comment by zamrokk** [comment]
need to change font policy to the one given by the Marigold UX PDF   

image


GA does not like this one

**Comment by zamrokk** [comment]
green or red when amount changes, please

**Comment by vanessamontesb** [comment]
@zamrokk  Updated.

**Pull request merged**
